# Generated by Django 5.2.1 on 2025-06-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_onboardingresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Тема")),
                ("body", models.TextField(verbose_name="Текст письма")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("sent", models.BooleanField(default=False, verbose_name="Отправлено")),
            ],
        ),
    ]
