version: "3.8"

services:
  backend:
    build:
      dockerfile: Dockerfile         # если имя отличается, укажите его
    container_name: achievka_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    build:
      dockerfile: Dockerfile
    container_name: achievka_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"                  # проброс порта 3000 на 3000
    env_file:
      - .env

  db:
    image: postgres:14
    container_name: pg_achievka_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
