# Generated by Django 5.2.1 on 2025-06-14 00:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "system"),
                            ("user", "user"),
                            ("assistant", "assistant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="letters.letterversion",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
