# Generated by Django 5.2.1 on 2025-06-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0003_draftletter_draftanswer_draftsection"),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="essay_prompt",
            field=models.TextField(
                blank=True, help_text="Только для common_app", null=True
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("generated", "Сгенерирована"),
                    ("locked", "Нужна подписка"),
                ],
                default="draft",
                help_text="Статус проверки письма",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="university",
            field=models.CharField(
                blank=True, help_text="Только для motivation", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="program",
            field=models.CharField(
                blank=True, help_text="Для motivation и ucas", max_length=255, null=True
            ),
        ),
    ]
