# Generated by Django 5.2.1 on 2025-05-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0002_scholarship_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
