# Generated by Django 5.2.1 on 2025-05-30 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0003_program_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarship",
            name="university",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scholarships",
                to="universities.university",
            ),
            preserve_default=False,
        ),
    ]
