# Generated by Django 5.2.1 on 2025-06-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0004_alter_scholarship_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="PNG-логотип университета",
                null=True,
                upload_to="university_logos/",
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Официальный сайт университета",
                max_length=500,
                null=True,
            ),
        ),
    ]
