# Generated by Django 5.2.1 on 2025-06-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0005_university_logo_university_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="min_act",
            field=models.CharField(
                blank=True, help_text="Минимальный балл ACT (если есть)", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="min_cambridge",
            field=models.CharField(
                blank=True,
                help_text="Требование по Cambridge Exam (например: 'Cambridge C1 Advanced')",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="min_gpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Минимальный GPA (если есть)",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="min_ib",
            field=models.CharField(
                blank=True,
                help_text="Требование по IB Diploma (например: 'Diploma required' или 'IB 30')",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="min_ielts",
            field=models.CharField(
                blank=True,
                help_text="Минимальный балл IELTS (если есть)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="min_sat",
            field=models.CharField(
                blank=True, help_text="Минимальный балл SAT (если есть)", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="min_toefl",
            field=models.CharField(
                blank=True,
                help_text="Минимальный балл TOEFL (если есть)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="official_link",
            field=models.URLField(
                blank=True, help_text="URL официальной страницы программы"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="duration",
            field=models.CharField(help_text="Например: '2 years'", max_length=50),
        ),
    ]
