# Generated by Django 5.2.1 on 2025-06-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0006_program_min_act_program_min_cambridge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="official_link",
            field=models.URLField(
                blank=True, help_text="URL официального сайта гранта"
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="programs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Программы, на которые распространяется этот грант",
                related_name="scholarships",
                to="universities.program",
            ),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="min_act",
            field=models.CharField(
                blank=True, help_text="Минимальный балл ACT (если есть)", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="min_ielts",
            field=models.CharField(
                blank=True,
                help_text="Минимальный балл IELTS (если есть)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="min_sat",
            field=models.CharField(
                blank=True, help_text="Минимальный балл SAT (если есть)", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="min_toefl",
            field=models.CharField(
                blank=True,
                help_text="Минимальный балл TOEFL (если есть)",
                max_length=10,
            ),
        ),
    ]
