# Generated by Django 5.2.1 on 2025-06-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "universities",
            "0007_scholarship_official_link_scholarship_programs_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scholarship",
            name="university",
        ),
        migrations.AddField(
            model_name="scholarship",
            name="universities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Университеты, в которые действует этот грант",
                related_name="scholarships",
                to="universities.university",
            ),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="min_act",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="min_ielts",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="min_sat",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="min_toefl",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
