# Generated by Django 5.2.1 on 2025-06-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0008_remove_scholarship_university_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="extra_requirements",
            field=models.TextField(blank=True),
        ),
    ]
