# Generated by Django 5.2.1 on 2025-06-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0009_scholarship_extra_requirements"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programfavorite",
            options={"ordering": ["-pinned", "order"]},
        ),
        migrations.AlterModelOptions(
            name="scholarshipfavorite",
            options={"ordering": ["-pinned", "order"]},
        ),
        migrations.AlterModelOptions(
            name="universityfavorite",
            options={"ordering": ["-pinned", "order"]},
        ),
        migrations.AddField(
            model_name="programfavorite",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Позиция в пользовательском списке favorites"
            ),
        ),
        migrations.AddField(
            model_name="programfavorite",
            name="pinned",
            field=models.BooleanField(
                default=False, help_text="Закреплён ли этот favorite вверху"
            ),
        ),
        migrations.AddField(
            model_name="programfavorite",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "В процессе подготовки"),
                    ("ready_to_apply", "Готов к подаче"),
                ],
                default="in_progress",
                help_text="Статус подготовки/подачи для данной программы",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scholarshipfavorite",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Позиция в пользовательском списке favorites"
            ),
        ),
        migrations.AddField(
            model_name="scholarshipfavorite",
            name="pinned",
            field=models.BooleanField(
                default=False, help_text="Закреплён ли этот favorite вверху"
            ),
        ),
        migrations.AddField(
            model_name="scholarshipfavorite",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "В процессе подготовки"),
                    ("ready_to_apply", "Готов к подаче"),
                ],
                default="in_progress",
                help_text="Статус подготовки/подачи для данного гранта",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="universityfavorite",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Позиция в пользовательском списке favorites"
            ),
        ),
        migrations.AddField(
            model_name="universityfavorite",
            name="pinned",
            field=models.BooleanField(
                default=False, help_text="Закреплён ли этот favorite вверху"
            ),
        ),
        migrations.AddField(
            model_name="universityfavorite",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "В процессе подготовки"),
                    ("ready_to_apply", "Готов к подаче"),
                ],
                default="in_progress",
                help_text="Статус подготовки/подачи для данного университета",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="min_cambridge",
            field=models.CharField(
                blank=True,
                help_text="Требование по Cambridge Exam (например: 'C1 Advanced')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="min_ib",
            field=models.CharField(
                blank=True,
                help_text="Требование по IB Diploma (например: 'IB 30')",
                max_length=20,
            ),
        ),
    ]
