name: CI/CD Docker → EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        run: |
          TAG=${{ github.sha }}
          REPO=${{ secrets.DOCKERHUB_USER }}/achievka_backend
          # билдим с двумя тегами
          docker build -t $REPO:$TAG -t $REPO:latest .
          docker push $REPO:$TAG
          docker push $REPO:latest

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/github_actions ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ${{ secrets.PROJECT_PATH }}

            # Тянем свежий образ
            docker-compose pull web

            # Останавливаем и удаляем старый контейнер web
            docker-compose stop web     || true
            docker-compose rm -f web     || true

            # Запускаем новый контейнер web
            docker-compose up -d web
          EOF
