name: CI/CD Docker → EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    # Прокидываем output из шага с id=build
    outputs:
      image: ${{ steps.build.outputs.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: build                    # <-- задаём идентификатор
        name: Build & push image
        run: |
          TAG=${{ github.sha }}
          IMAGE="${{ secrets.DOCKERHUB_USER }}/your-app:$TAG"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          # Записываем IMAGE в output этого шага
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

  deploy:
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions.pub
          chmod 600 ~/.ssh/github_actions.pub
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/github_actions ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ${{ secrets.PROJECT_PATH }}
            IMAGE=${{ needs.build-push.outputs.image }}
            sed -i "s|image: .*|image:$IMAGE|" docker-compose.yml
            docker-compose pull web
            docker-compose up -d
          EOF
