name: CI/CD Docker → EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: DOCKERHUB_USER
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        run: |
          TAG=${{ github.sha }}
          IMAGE=${{ secrets.DOCKERHUB_USER }}/your-app:$TAG
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "::set-output name=image::$IMAGE"

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ${{ secrets.PROJECT_PATH }}
            IMAGE=${{ needs.build-push.outputs.image }}
            # подменяем образ в docker-compose.yml:
            sed -i "s|image: .*|image: $IMAGE|g" docker-compose.yml
            docker-compose pull web
            docker-compose up -d
          EOF
